[package]
name = "zman"
version = "1.0.6"
authors = ["azzamsa <me@azzamsa.com>"]
categories = ["date-and-time", "command-line-utilities"]
edition = "2018"
keywords = ["time", "year", "progress-bar"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/azzamsa/zman"
description = "a CLI year progress "

[profile.release]
opt-level = 'z' # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[dependencies]
chrono = "0.4.18"
colored = "2.0.0"

[dependencies.clap]
version = "4.0.29"
features = ["suggestions", "color", "cargo", "derive"]

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.4"
