[package]
name = "zman"
description = "a CLI year progress "
version = "1.0.4"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2018"
keywords = ["time", "year", "progress-bar"]
categories = ["date-and-time", "command-line-utilities"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://github/azzamsa/zman"

[profile.release]
opt-level = 'z'  # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[dependencies]
chrono = "0.4.18"
colored = "2.0.0"

[dependencies.clap]
version = "2.33.3"
default-features = false
features = ["suggestions"]

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.7"
