[package]
name = "zman"
version = "0.1.2"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.18"
clap = "3.0.0-beta.2"
colored = "2.0.0"
