# tested against
# i3status-rs 0.14.3 (commit b98c99e 2020-12-10)

[icons]
name = "awesome5"
[icons.overrides]
zman = "  "

[[block]]
block = "custom"
cycle = [
        "zman year -J",
        "zman month -J",
        "zman week -J",
        ]
on_click = "<command>"
interval = 300
json = true
